export const USER_LOGIN = 'USER_LOGIN';

export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';

export const EXCHANGE_RATES = 'EXCHANGE_RATES';

export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';

export const EDIT_EXPENSE = 'EDIT_EXPENSE';

export const EDITED_EXPENSE = 'EDITED_EXPENSE';
